apiVersion: v1
kind: Service
metadata:
  labels:
    visualize: "true"
  name: turfgame-stats-service
spec:
  selector:
    app: turfgame-stats
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer